///* =========================================================
// * ====                   WARNING                        ===
// * =========================================================
// * The code in this tab has been generated from the GUI form
// * designer and care should be taken when editing this file.
// * Only add/edit code inside the event handlers i.e. only
// * use lines between the matching comment tags. e.g.

// void myBtnEvents(GButton button) { //_CODE_:button1:12356:
//     // It is safe to enter your event code here  
// } //_CODE_:button1:12356:
 
// * Do not rename this tab!
// * =========================================================
// */

//public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:820032:
////  println("button1 - GButton >> GEvent." + event + " @ " + millis());
//} //_CODE_:button1:820032:

//public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:textfield1:900874:
//  println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());
//} //_CODE_:textfield1:900874:

//public void slider1_change1(GSlider source, GEvent event) { //_CODE_:slider1:496010:
//  println("slider1 - GSlider >> GEvent." + event + " @ " + millis());
//} //_CODE_:slider1:496010:



//// Create all the GUI controls. 
//// autogenerated do not edit
//public void createGUI(){
//  G4P.messagesEnabled(false);
//  G4P.setGlobalColorScheme(GCScheme.PURPLE_SCHEME);
//  G4P.setMouseOverEnabled(false);
//  surface.setTitle("Sketch Window");
//  button1 = new GButton(this, 4, 346, 80, 30);
//  button1.setText("Face text");
//  button1.addEventHandler(this, "button1_click1");
//  textfield1 = new GTextField(this, 270, 349, 120, 30, G4P.SCROLLBARS_NONE);
//  textfield1.setText("Conways Game of Life");
//  textfield1.setPromptText("GOL");
//  textfield1.setOpaque(true);
//  textfield1.addEventHandler(this, "textfield1_change1");
//  slider1 = new GSlider(this, 99, 343, 163, 40, 10.0);
//  slider1.setLimits(0.5, 0.0, 1.0);
//  slider1.setNumberFormat(G4P.DECIMAL, 2);
//  slider1.setOpaque(false);
//  slider1.addEventHandler(this, "slider1_change1");
//}

//// Variable declarations 
//// autogenerated do not edit
//GButton button1; 
//GTextField textfield1; 
//GSlider slider1; 
